import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import GlowingCursor from "./components/GlowingCursor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "DEVELOPER SADHIN",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
           <Navbar/>
        </header>
        <main className="pt-16 text-white bg-gray-900 ">
          <div className="px-6  max-w-7xl mx-auto min-h-[calc(100vh-341px)]">
               <GlowingCursor/>
               {children}
          </div>
        </main>
        <Footer/>
      </body>
    </html>
  );
}
